export const table = [
   {
      "numberTable": 105,
      "quantity": 6,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 30,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "1"
   },
   {
      "numberTable": 106,
      "quantity": 4,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 9,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "2"
   },
   {
      "numberTable": 107,
      "quantity": 14,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 55,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "3"
   },
   {
      "numberTable": 108,
      "quantity": 14,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 12,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "4"
   },
   {
      "numberTable": 109,
      "quantity": 8,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 15,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "5"
   },
   {
      "numberTable": 110,
      "quantity": 8,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 65,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "6"
   },
   {
      "numberTable": 111,
      "quantity": 6,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 48,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "7"
   },
   {
      "numberTable": 112,
      "quantity": 6,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 44,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "8"
   },
   {
      "numberTable": 113,
      "quantity": 8,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 69,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "9"
   },
   {
      "numberTable": 114,
      "quantity": 6,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 1,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "10"
   },
   {
      "numberTable": 115,
      "quantity": 6,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 21,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "11"
   },
   {
      "numberTable": 116,
      "quantity": 2,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 58,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "12"
   },
   {
      "numberTable": 117,
      "quantity": 2,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 1,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "13"
   },
   {
      "numberTable": 118,
      "quantity": 2,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 2,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "14"
   },
   {
      "numberTable": 119,
      "quantity": 2,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 4,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "15"
   },
   {
      "numberTable": 120,
      "quantity": 4,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 55,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "16"
   },
   {
      "numberTable": 121,
      "quantity": 12,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 61,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "17"
   },
   {
      "numberTable": 122,
      "quantity": 12,
      "status": 5,
      "seat": 0,
      "percent": 0,
      "timeOrder": 21,
      "idCustomer": 0,
      "timeList": [],
      "timeSeated": 0,
      "updateBack": 0,
      "id": "18"
   }
]