import Head from 'next/head'
import App from '../components'

const Home = () => {
  return (
    <>
      <Head>
        <title>Floor Plan View</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <App />
    </>
  )
}

export default Home
