import Head from 'next/head';
import App from '../components';
import { Provider } from 'react-redux';
import store from '../redux/store';
import SocketContextComponent from '../socket/contexts/SocketContextComponent';

const Home = () => {
    return (
        <>
            <Head>
                <title>Floor Plan View</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <meta
                    name="viewport"
                    content="width=device-width, initial-scale=1.0, viewport-fit=cover"
                />
                <link rel="icon" href="/favicon.ico" />
                <link
                    href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
                    rel="stylesheet"
                />
            </Head>

            <SocketContextComponent>
                <Provider store={store}>
                    <App />
                </Provider>
            </SocketContextComponent>
        </>
    );
};

export default Home;
