// import type { NextPage } from 'next'
import Head from 'next/head'
import ApiContextProvider from './ApiContext'
import Header from '../components/header'
import Content from '../components/content'

const Home = () => {
  return (
    <>
      <Head>
        <title>Floor Plan View</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ApiContextProvider>
        <Header />
        <Content />
      </ApiContextProvider>
    </>
  )
}

export default Home
